name: Kwenta CI

on:
  push:
  pull_request:
    branches: [master, dev, v2, v2-dev]

jobs:
  audit:
    # run only on master/dev/v2/v2-dev branch and pull requests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-sec-tools/base:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Audit dependencies
        run: npm audit --audit-level=critical

      - name: Lockfile lint
        run: lockfile-lint -p package-lock.json --type npm --allowed-hosts npm github.com --allowed-schemes "https:" "git+ssh:" "npm:"

  lint:
    needs: audit
    # run only on audit success or audit skipped
    if: always() && (needs.audit.result == 'success' || needs.audit.result == 'skipped')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0 # pin@v3
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-cache-
        continue-on-error: true

      # fixes permission issues on gh actions + docker + npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      # mkdir -p node_modules fixes https://github.com/npm/cli/issues/3208 starting from npm@7
      - name: Install dependencies
        run: |
          mkdir -p node_modules
          npm install --prefer-offline --no-audit --legacy-peer-deps

      - name: Lint
        # run only on master/dev/v2/v2-dev branch and pull requests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        run: npm run lint:sarif

      - name: Upload lint results
        # run if lint failed and only on master/dev/v2/v2-dev branch and pull requests
        if: always() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev')
        uses: github/codeql-action/upload-sarif@81bfc289f5947eca8a3358341c874cb4f4697b64 # pin@codeql-bundle-20220322
        with:
          sarif_file: lint-results.sarif
        continue-on-error: true

      - name: Unit tests
        # run only on master/dev/v2/v2-dev branch and pull requests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        run: npm run test:unit

  build:
    needs: lint
    # run only on lint success or lint skipped
    if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/synthetixio/docker-node/alpine:16.14
      credentials:
        username: synthetixio
        password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0 # pin@v3
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-cache-
        continue-on-error: true

      # fixes permission issues on gh actions + docker + npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      # mkdir -p node_modules fixes https://github.com/npm/cli/issues/3208 starting from npm@7
      - name: Install dependencies
        run: |
          mkdir -p node_modules
          npm install --prefer-offline --no-audit --legacy-peer-deps

      - name: Cache next.js build cache
        uses: actions/cache@136d96b4aee02b1f0de3ba493b1d47135042d9c0 # pin@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: Compress build
        run: tar -zcvf build.tar.gz .next

      - name: Archive build
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/v2-dev'
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # pin@v3
        with:
          name: build
          path: build.tar.gz
