name: Kwenta CI

on:
  push:
  pull_request:
    branches: [main, dev]

jobs:
  audit:
    # run only on main/dev branch and pull requests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-sec-tools:16.14-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v2

      - name: Audit dependencies
        run: npm audit --audit-level=critical

      - name: Lockfile lint
        run: lockfile-lint -p package-lock.json --type npm --allowed-hosts npm github.com --allowed-schemes "https:" "git+ssh:" "npm:"

  lint:
    needs: audit
    # run only on audit success or audit skipped
    if: always() && (needs.audit.result == 'success' || needs.audit.result == 'skipped')
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-node:16.14-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # pin@v3
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-cache-
        continue-on-error: true

      # fixes permission issues on gh actions + docker + npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      # mkdir -p node_modules fixes https://github.com/npm/cli/issues/3208 starting from npm@7
      - name: Install dependencies
        run: |
          mkdir -p node_modules
          npm install --prefer-offline --no-audit --legacy-peer-deps

      - name: Lint
        # run only on main/dev branch and pull requests
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
        run: npm run lint:sarif

      - name: Upload lint results
        # run if lint failed and only on main/dev branch and pull requests
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request')
        uses: github/codeql-action/upload-sarif@807578363a7869ca324a79039e6db9c843e0e100 # pin@codeql-bundle-20220322
        with:
          sarif_file: lint-results.sarif
        continue-on-error: true

      - name: Unit tests
        # run only on main/dev branch and pull requests
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
        run: npm run test:unit

  build:
    needs: lint
    # run only on lint success or lint skipped
    if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-node:16.14-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v2

      - name: Set npm cache directory
        run: npm config set cache .npm-cache --global
        continue-on-error: true

      - name: Cache node modules
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # pin@v3
        with:
          path: |
            .npm-cache
            node_modules
          key: ${{ runner.os }}-alpine-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-alpine-cache-
        continue-on-error: true

      # fixes permission issues on gh actions + docker + npm@8
      - name: Chown workspace
        run: chown -R $(whoami) .

      # mkdir -p node_modules fixes https://github.com/npm/cli/issues/3208 starting from npm@7
      - name: Install dependencies
        run: |
          mkdir -p node_modules
          npm install --prefer-offline --no-audit --legacy-peer-deps

      - name: Cache next.js build cache
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # pin@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-cache-
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: Compress build
        run: tar -zcvf build.tar.gz .next

      - name: Archive build
        uses: actions/upload-artifact@v3 # pin@v3
        with:
          name: build
          path: build.tar.gz

  e2e:
    needs: build
    # run only on main/dev branch
    if: always() && (needs.build.result == 'success')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        resolution: ['high']

    steps:
      - name: Chown workspace
        run: chown -R $(whoami) .

      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # pin@v1

      - name: Cache Docker \layers
        uses: actions/cache@56461b9eb0f8438fd15c7a9968e3c9ebb18ceff1 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run e2e tests (${{ matrix.resolution }} resolution)
        run: |
          docker-compose --env-file ./${{ matrix.resolution }}-res.env up --build --exit-code-from synpress
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          DOCKER_DEFAULT_PLATFORM: linux/amd64
          PRIVATE_KEY: ${{ env.PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NGROK_AUTH: ${{ secrets.NGROK_AUTH }}

      - name: Archive e2e artifacts (${{ matrix.resolution }} resolution)
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v2
        if: always()
        with:
          name: e2e-artifacts-${{ matrix.resolution }}-resolution
          path: |
            docker/videos
            docker/videos-ci
            docker/screenshots
        continue-on-error: true
