name: Lighthouse scan

on:
  workflow_dispatch:
    inputs:
      url:
        description: Url of website to scan
        required: true
        default: https://kwenta.eth.limo

jobs:
  lighthouse_scan:
    runs-on: ubuntu-latest

    container:
      image: synthetixio/docker-e2e:16.14-ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v2

      - name: Run lighthouse
        run: |
          lhci autorun --config=tests/lighthouse/lhci-desktop.conf.js
          lhci autorun --config=tests/lighthouse/lhci-mobile.conf.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_URL: ${{ github.event.inputs.url }}
        continue-on-error: true

      - name: Archive lighthouse artifacts
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # pin@v2
        # run on lighthouse fail
        if: always()
        with:
          name: lighthouse-reports
          path: |
            .lighthouseci
            lighthouse-desktop-report
            lighthouse-mobile-report
        continue-on-error: true
